### ISSUE TITLE
FCM 환경 구축 - frontend

### ISSUE THREAD

**Issue by Boknami** [Beacon-2023/Beacon-frontend#10]

**Comment by minsang-alt** [comment]
이메일로 firebase 프로젝트에 초대했습니다

**Comment by Boknami** [comment]
![tkn](https://github.com/Beacon-2023/Beacon-frontend/assets/60930743/c8417c0c-47f2-4acc-b043-395af8664057)

FCM 토큰 정보 확인

**Comment by Boknami** [comment]
## FCM수신 TEST

![image](https://github.com/Beacon-2023/Beacon-frontend/assets/60930743/7f2d2f05-082f-4770-99dc-458eacbf5750)


6분 정도의 딜레이 발생

**Comment by minsang-alt** [comment]
fcm에서 보내는 푸시알람이 기기에 도착하는데 6분이나 딜레이 생기나요?
@Boknami

**Comment by Boknami** [comment]
넵 정상 기능 작동 확인을 위해
fcm 클라우드 테스트 메시지를 보내서 확인했는데,초 단위 안에는 도착할 수 있게 내일 원인 파악 및 수정해서 결과 올릴 예정입니다!

@minsang-alt

**Comment by Boknami** [comment]
## FCM 지연 발생

![image](https://github.com/Beacon-2023/Beacon-frontend/assets/60930743/1153612a-cfa2-4b57-9ab3-ab3194f86093)

FCM 클라우드 메시지 자체에서 발생할 때 생기는 딜레이가 길게는 1분까지 발생한다 쳐도 도착 시간이 느림.
재난 상황 발생 시 빠르게 사용자에게 알려주기 위해서는 이 정도 딜레이는 심각하다.

발생 시간을 단축할 수 있도록 테스트 진행중.
1. 테스트 기기 문제?
2. 권한
3. 코드끼리 꼬임
4. 절전모드

등의 원인이 예상되고 하나씩 다른 방법으로 재시도 예정
