### ISSUE TITLE
백그라운드에서의 알림 서비스

### ISSUE THREAD

**Issue by Boknami** [Beacon-2023/Beacon-frontend#5]
## 알림 전송 단계
![image](https://github.com/Beacon-2023/Beacon-frontend/assets/60930743/7c9a1cd6-9700-44cf-b947-6f851705a5b2)

---

## 알림 전송의  문제
최종적으로 알림을 사용자에게 보내야 하는데 앱이 계속 켜져있는 상태라면 초마다 갱신을 할 수 있는 코드를 적용하면 되지만 보통 앱을 계속 키고 있지는 않는다.

##해결방안
1. 백그라운드에서 앱이 작동하며 일정 초마다 확인한다.
=> 문제 : Android M(API 23)부터 백그라운드 작업에 제약사항들이 생김
=> 대안 : WorkManager를 사용한다. 워크매니저는 서버에게 데이터 전송 또는 서버 동기화, 이미지 저장 등 작업을 프로세스 종료와 상관없이 작업 진행이 가능.

2. FCM을 이용한 백그라운드 알림 전송

**Comment by Boknami** [comment]
![image](https://github.com/Beacon-2023/Beacon-frontend/assets/60930743/80ee9511-a6b9-46bf-83bc-9cb66c83e302)

# 논의 내용
1. 회원가입자들은 이미 DB에 위치 정보가 있어서 서버에서 재난 내용을 확인하고 바로 보낼 수 있지만
비회원들과 동일하게 위치 정보를 보낼 것인가?

2. workManger 적정 갱신 시간

**Comment by minsang-alt** [comment]
해당 이슈는 다른 문제없이 구현이 잘되면 종료하는걸로 하겠습니다
